name: Build
on: {push: {branches: [gh-pages]}}

jobs:
  build:
    runs-on: ubuntu-20.04
    container: node:16-buster
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install
      run: |
        npm install
    - name: Build
      run: |
        npm run browserify
        sed -i 's/kfw\.js/kfw.dist.js/g' kobofirmware.html
        touch .nojekyll
    - name: Deploy
      run: |
        git config user.name "GitHub Actions"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git checkout --orphan gh-pages-dist
        git reset
        git add .nojekyll kfw.css kfw.db.js kfw.dist.js kfw.dist.js.map kobofirmware.html
        git commit -m "Build ${{github.sha}}"
        git push -u origin gh-pages-dist --force
